### ISSUE TITLE
debug mode not possible in pycharm 

### ISSUE THREAD

**Issue by jeremy-rutman** [simphony/simphony-common#192]
I've been using print statements for debugging as I can't seem to use the pycharm IDE debugger, apparently due to a pycharm issue that i've seen only when coding for simphony  - anyone else run into this/have a workaround (besides print statements....)??  

/usr/bin/python2.7 /usr/local/lib/pycharm-community-4.0.6/helpers/pydev/pydevd.py --multiproc --client 127.0.0.1 --port 43960 --file /usr/local/lib/pycharm-community-4.0.6/helpers/pycharm/utrunner.py /home/jeremy/Dropbox/projects/simphony/simphony_code/simphony-quantum-espresso/simphony-espresso-dft/simespresso/io/unittest_parse_QE_input.py true
Testing started at 2:15 PM ...
Traceback (most recent call last):
  File "/usr/local/lib/pycharm-community-4.0.6/helpers/pydev/pydevd.py", line 12, in <module>
    import pydev_imports
  File "/usr/local/lib/pycharm-community-4.0.6/helpers/pydev/pydev_monkey_qt.py", line 71, in patched_import
    return original_import(name, *args, **kwargs)
  File "/usr/local/lib/pycharm-community-4.0.6/helpers/pydev/pydev_imports.py", line 9, in <module>
    import xmlrpclib
  File "/usr/local/lib/pycharm-community-4.0.6/helpers/pydev/pydev_monkey_qt.py", line 71, in patched_import
    return original_import(name, *args, **kwargs)
  File "/usr/lib/python2.7/xmlrpclib.py", line 146, in <module>
    import gzip
  File "/usr/local/lib/pycharm-community-4.0.6/helpers/pydev/pydev_monkey_qt.py", line 71, in patched_import
    return original_import(name, *args, **kwargs)
  File "/usr/lib/python2.7/gzip.py", line 36, in <module>
    class GzipFile(io.BufferedIOBase):
AttributeError: 'module' object has no attribute 'BufferedIOBase'

**Comment by jeremy-rutman** [comment]
looks like its not a good idea to call your module io.py 

from https://youtrack.jetbrains.com/issue/PY-2131

>It turns out that when running a program in debug, one of the python libraries that gets called in is also >called io, so the io.py in my directory was searched for what was supposed to be obtained in the system >io.py code.
