### ISSUE TITLE
wrong reqirements for Tables

### ISSUE THREAD

**Issue by ahashibon** [simphony/simphony-common#389]
when doing pip install -r requirements from branch #fix-numpy-dependency we get: 

```
You are using pip version 7.1.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting numexpr (from -r requirements.txt (line 1))
Collecting enum34>=1.0.4 (from -r requirements.txt (line 2))
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting tables>=3.1.1 (from -r requirements.txt (line 3))
  Using cached tables-3.3.0.tar.gz
Collecting stevedore>=1.2.0 (from -r requirements.txt (line 4))
  Using cached stevedore-1.20.0-py2.py3-none-any.whl
Collecting numpy==1.11.1 (from -r requirements.txt (line 5))
Collecting six (from tables>=3.1.1->-r requirements.txt (line 3))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pbr>=1.8 (from stevedore>=1.2.0->-r requirements.txt (line 4))
  Using cached pbr-1.10.0-py2.py3-none-any.whl
Building wheels for collected packages: tables
  Running setup.py bdist_wheel for tables
  Complete output from command /home/has/simphony/bin/python -c "import setuptools;__file__='/tmp/pip-build-iR0JiQ/tables/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp8C6UFBpip-wheel-:
  /tmp/lzo_version_dateIS8NFg.c:1:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
   main (int argc, char **argv) {
   ^
  /tmp/lzo_version_dateIS8NFg.c: In function ‘main’:
  /tmp/lzo_version_dateIS8NFg.c:2:5: warning: implicit declaration of function ‘lzo_version_date’ [-Wimplicit-function-declaration]
       lzo_version_date();
       ^
  /usr/bin/ld: cannot find -llzo2
  collect2: error: ld returned 1 exit status
  /tmp/lzo_version_dateNGbOMC.c:1:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
   main (int argc, char **argv) {
   ^
  /tmp/lzo_version_dateNGbOMC.c: In function ‘main’:
  /tmp/lzo_version_dateNGbOMC.c:2:5: warning: implicit declaration of function ‘lzo_version_date’ [-Wimplicit-function-declaration]
       lzo_version_date();
       ^
  /usr/bin/ld: cannot find -llzo
  collect2: error: ld returned 1 exit status
  /tmp/BZ2_bzlibVersionRIyhqn.c:1:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
   main (int argc, char **argv) {
   ^
  /tmp/BZ2_bzlibVersionRIyhqn.c: In function ‘main’:
  /tmp/BZ2_bzlibVersionRIyhqn.c:2:5: warning: implicit declaration of function ‘BZ2_bzlibVersion’ [-Wimplicit-function-declaration]
       BZ2_bzlibVersion();
       ^
  /usr/bin/ld: cannot find -lbz2
  collect2: error: ld returned 1 exit status
  /tmp/blosc_list_compressorsUHxWfi.c:1:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
   main (int argc, char **argv) {
   ^
  /tmp/blosc_list_compressorsUHxWfi.c: In function ‘main’:
  /tmp/blosc_list_compressorsUHxWfi.c:2:5: warning: implicit declaration of function ‘blosc_list_compressors’ [-Wimplicit-function-declaration]
       blosc_list_compressors();
       ^
  /usr/bin/ld: cannot find -lblosc
  collect2: error: ld returned 1 exit status
  * Using Python 2.7.12 (default, Nov 19 2016, 06:48:10)
  * USE_PKGCONFIG: True
  * pkg-config header dirs for HDF5: /usr/include/hdf5/serial
  * pkg-config library dirs for HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial
  * Found HDF5 headers at ``/usr/include/hdf5/serial``, library at ``/usr/lib/x86_64-linux-gnu/hdf5/serial``.
  .. WARNING:: Could not find the HDF5 runtime.
     The HDF5 shared library was *not* found in the default library
     paths. In case of runtime problems, please remember to install it.
  * Could not find LZO 2 headers and library; disabling support for it.
  * Could not find LZO 1 headers and library; disabling support for it.
  * Could not find bzip2 headers and library; disabling support for it.
  * Could not find blosc headers and library; using internal sources.
  SSE2 detected
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/tables
  copying tables/description.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/link.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/filters.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/atom.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/node.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/table.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/parameters.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/conditions.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/expression.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/index.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/idxutils.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/group.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/carray.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/leaf.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/undoredo.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/array.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/file.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/unimplemented.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/vlarray.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/req_versions.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/flavor.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/registry.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/exceptions.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/attributeset.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/earray.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/path.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/__init__.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/utils.py -> build/lib.linux-x86_64-2.7/tables
  copying tables/indexes.py -> build/lib.linux-x86_64-2.7/tables
  creating build/lib.linux-x86_64-2.7/tables/scripts
  copying tables/scripts/ptrepack.py -> build/lib.linux-x86_64-2.7/tables/scripts
  copying tables/scripts/ptdump.py -> build/lib.linux-x86_64-2.7/tables/scripts
  copying tables/scripts/pttree.py -> build/lib.linux-x86_64-2.7/tables/scripts
  copying tables/scripts/__init__.py -> build/lib.linux-x86_64-2.7/tables/scripts
  copying tables/scripts/pt2to3.py -> build/lib.linux-x86_64-2.7/tables/scripts
  creating build/lib.linux-x86_64-2.7/tables/misc
  copying tables/misc/proxydict.py -> build/lib.linux-x86_64-2.7/tables/misc
  copying tables/misc/enum.py -> build/lib.linux-x86_64-2.7/tables/misc
  copying tables/misc/__init__.py -> build/lib.linux-x86_64-2.7/tables/misc
  creating build/lib.linux-x86_64-2.7/tables/nodes
  copying tables/nodes/filenode.py -> build/lib.linux-x86_64-2.7/tables/nodes
  copying tables/nodes/__init__.py -> build/lib.linux-x86_64-2.7/tables/nodes
  creating build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_vlarray.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_enum.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/check_leaks.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_numpy.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_all.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_earray.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/common.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_indexes.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_garbage.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_array.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_aux.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_expression.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_create.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_nestedtypes.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/create_backcompat_indexes.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_timetype.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_tree.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_do_undo.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_hdf5compat.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_lists.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_links.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_backcompat.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_types.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_carray.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/__init__.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_queries.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_tablesMD.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_basics.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_attributes.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_indexvalues.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_index_backcompat.py -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_tables.py -> build/lib.linux-x86_64-2.7/tables/tests
  creating build/lib.linux-x86_64-2.7/tables/nodes/tests
  copying tables/nodes/tests/test_filenode.py -> build/lib.linux-x86_64-2.7/tables/nodes/tests
  copying tables/nodes/tests/__init__.py -> build/lib.linux-x86_64-2.7/tables/nodes/tests
  copying tables/tests/elink.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/oldflavor_numeric.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/times-nested-be.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/smpl_enum.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/zerodim-attrs-1.3.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/attr-u16.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/smpl_i32be.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/smpl_unsupptype.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/elink2.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/float.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/smpl_f64be.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/bug-idx.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/smpl_compound_chunked.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/issue_368.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/time-table-vlarray-1_x.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/python3.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/python2.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/smpl_f64le.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/smpl_SDSextendible.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/zerodim-attrs-1.4.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/smpl_i32le.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/indexes_2_1.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/non-chunked-table.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_szip.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/issue_560.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/idx-std-1.x.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/flavored_vlarrays-format1.6.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/slink.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/vlstr_attr.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/Tables_lzo2.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/Tables_lzo1_shuffle.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/Table2_1_lzo_nrv2e_shuffle.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/smpl_i64le.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/indexes_2_0.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/Tables_lzo1.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/nested-type-with-gaps.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/array_mdatom.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/smpl_i64be.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/Tables_lzo2_shuffle.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/blosc_bigendian.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/scalar.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/vlunicode_endian.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/ex-noattr.h5 -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/matlab_file.mat -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_ref_array2.mat -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/tests/test_ref_array1.mat -> build/lib.linux-x86_64-2.7/tables/tests
  copying tables/nodes/tests/test_filenode.dat -> build/lib.linux-x86_64-2.7/tables/nodes/tests
  copying tables/nodes/tests/test_filenode.xbm -> build/lib.linux-x86_64-2.7/tables/nodes/tests
  copying tables/nodes/tests/test_filenode_v1.h5 -> build/lib.linux-x86_64-2.7/tables/nodes/tests
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-iR0JiQ/tables/setup.py", line 994, in <module>
      **setuptools_kwargs
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/has/simphony/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 175, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-iR0JiQ/tables/setup.py", line 61, in run
      numpy_incl = pkg_resources.resource_filename('numpy', 'core/include')
    File "/home/has/simphony/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1160, in resource_filename
      return get_provider(package_or_requirement).get_resource_filename(
    File "/home/has/simphony/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 435, in get_provider
      __import__(moduleOrReq)
  ImportError: No module named numpy
  
  ----------------------------------------
  Failed building wheel for tables
Failed to build tables
Installing collected packages: numpy, numexpr, enum34, six, tables, pbr, stevedore
  Running setup.py install for tables
  Successfully installed enum34-1.1.6 numexpr-2.6.2 numpy-1.11.1 pbr-1.10.0 six-1.10.0 stevedore-1
```

**Comment by stefanoborini** [comment]
Linux which version?

**Comment by stefanoborini** [comment]
Ubuntu 16.04.1 LTS

**Comment by stefanoborini** [comment]
This has been solved by not using a cache version of tables to build.
