### ISSUE TITLE
The repository fails tests

### ISSUE THREAD

**Issue by 8thMage** [simphony/simphony-common#429]
Hi,
I installed all of the requirements and used setup.py to install the project, then i ran sudo python -m unittest discover and it gave me a failure message::
======================================================================
ERROR: simphony.tools.tests.test_lattice_tools (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: simphony.tools.tests.test_lattice_tools
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/home/edensegal/simphony-common/simphony/tools/tests/test_lattice_tools.py", line 5, in <module>
    from hypothesis import given, settings
ImportError: No module named hypothesis

----------------------------------------------------------------------
Ran 673 tests in 85.338s

FAILED (errors=1, skipped=3)

Is it imprtant?
also there is a lot of warnings i can paste if someone wants to look at them.

**Comment by Pablo-amz** [comment]
Hey,
It looks like you don't have the hypotheses library installed. 
You can install it by running `pip install hypothesis`, and that should do it. 
Make sure you have enough rights so the installation can actually modify the needed folders, though.
